import Head from 'next/head'
import { useState, useEffect } from 'react'
import { useDataContext } from '@/components/BigContainer/useDataContext'
import Brand from '@/components/Brand'
import Products from '@/components/Products'
import { getDoc } from 'firebase/firestore'
import { useFirebase } from '@/Firebase/useFirebase'
import { BiSolidDrink } from "react-icons/bi"
import { PiBathtubBold } from "react-icons/pi"
import { MdPets, MdOutlineLocalPharmacy } from "react-icons/md"
import Link from 'next/link'
import Aos from 'aos'
import 'aos/dist/aos.css'
import Newsletter from '@/components/Newsletter'


export default function Home({ }) {

  const [data, setData] = useState([])
  const { dataApi, setDataUserConnected } = useDataContext()
  const { userConnect, uid, user } = useFirebase()

  useEffect(() => {
    setData(dataApi)

    Aos.init({duration: 2000})
  }, [])

  useEffect(() => {
    if (userConnect) {
      // Update state data of the user connected
      getDoc(user(uid))
        .then(doc => {
          if (doc.exists()) {
            setDataUserConnected(doc.data())
          }
        })
    }
  }, [userConnect])



  //Packaged products
  const PackagedProductsData = data && data.filter(item => item.category === 'Packaged products')
  const drunkData = data && data.filter(item => item.category === 'Drunks')
  const vegetableData = data && data.filter(item => item.category === 'Fruits and Vegetables')
  const higieneCareData = data && data.filter(item => item.category === 'Hygiene and personal care')


  return (
    <>
      <Head>
        <title>Shaws</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Brand />

        <div className='mt-72 md:mt-60 lg:mt-36'>
          <div className='flex gap-4 md:gap-6 lg:gap-8 px-5 mb-5 text-3xl font-bold text-sky-950 items-center lg:px-32'>
            <h1>Most Popular</h1>
            <p className='w-20 h-1 bg-green-700'></p>
          </div>
          <div className='grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 md:gap-6 lg:gap-8 xl:gap-12 justify-center items-center px-5 lg:px-56'>
            <Link href={"/category/drunks"} className="flex flex-col gap-4 items-center px-2 py-6 shadow-md hover:shadow-lg border border-gray-100" data-aos="fade-up">
              <span className='text-6xl text-blue-400'> <BiSolidDrink /> </span>
              <p className='text-sm text-black'>
                Drinks, Alcohol, Energy
              </p>
            </Link>
            <Link href={"/"} className="flex flex-col gap-4 items-center px-2 py-6 shadow-md hover:shadow-lg border border-gray-100" data-aos="fade-down">
              <span className='text-6xl text-blue-400'> <PiBathtubBold /> </span>
              <p className='text-sm text-black'>
                Hygiene, Personal care
              </p>
            </Link>
            <Link href={"/"} className="flex flex-col gap-4 items-center px-2 py-6 shadow-md hover:shadow-lg border border-gray-100" data-aos="fade-up">
              <span className='text-6xl text-blue-400'> <MdPets /> </span>
              <p className='text-sm text-black'>
                Pets, Domestic, Dog, Cat
              </p>
            </Link>
            <Link href={"/"} className="flex flex-col gap-4 items-center px-2 py-6 shadow-md hover:shadow-lg border border-gray-100" data-aos="fade-down">
              <span className='text-6xl text-blue-400'> <MdOutlineLocalPharmacy /> </span>
              <p className='text-sm text-black'>
                Health, Pharmacy
              </p>
            </Link>
          </div>
        </div>

        {
          <div className='mt-28 md:mt-40 xl:mt-36'>
            <div className='flex gap-3 px-5 mb-5 text-xl lg:text-3xl font-bold text-sky-950 items-center lg:px-32'>
              <h1>Fruits and vegetables</h1>
              <p className='w-20 h-1 bg-green-700'></p>
            </div>
            <Products product={vegetableData} />
          </div>
        }
        <div className='mt-28 flex px-4 py-4 mx-5 lg:mx-20 xl:mx-48 gap-6 items-center justify-between  bg-green-600 rounded-md'>
          <p className='text-white text-md md:text-xl font-bold'>Fusce congue lorem id porta volutpat.</p>
          <button className="bg-orange-400 text-white px-2 sm:px-5 py-3 text-sm sm:text-md lg:text-lg font-bold rounded"> Shop now </button>
        </div>
        {
          <div className='mt-28'>
            <div className='flex gap-3 px-5 mb-5 text-xl lg:text-3xl font-bold text-sky-950 items-center lg:px-32'>
              <h1>Packaged products</h1>
              <p className='w-20 h-1 bg-green-700'></p>
            </div>
            <Products product={PackagedProductsData} />
          </div>
        }
        <Newsletter />
      </main>
    </>
  )
}
