import Head from 'next/head'
import { useState, useEffect } from 'react'
import { useDataContext } from '@/components/BigContainer/useDataContext'
import Brand from '@/components/Brand'
import Products from '@/components/Products'


export default function Home({ }) {

  const [data, setData] = useState([])
  let recommended = []
  const { dataApi } = useDataContext()

  useEffect(() => {
    setData(dataApi)
  }, [])

  // Fill the table recommended
  if(data){
    for (let i = 0; i < 10; i++) {
      let index
      index = Math.floor(Math.random() * data.length)
      if(recommended.length >= 1){
        if(recommended[i - 1] !== undefined){
          let finding = recommended.findIndex(obj => obj.id === index)
          while(finding !== -1){
            index = Math.floor(Math.random() * data.length)
            finding = recommended.findIndex(obj => obj.id === index)
          }
        }
      }
      recommended.push(data[index])
    }
  }

  //Packaged products
  const PackagedProductsData = data && data.filter(item => item.category === 'Packaged products')
  const drunkData = data && data.filter(item => item.category === 'Drunks')
  const vegetableData = data && data.filter(item => item.category === 'Fruits and Vegetables')
  const higieneCareData = data && data.filter(item => item.category === 'Hygiene and personal care')


  return (
    <>
      <Head>
        <title>Shaws</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Brand />
        {
          !(recommended[0] == undefined) && <div className='mt-72 md:mt-40 xl:mt-36'>
            <div className='flex gap-3 px-5 mb-5 text-3xl font-bold text-sky-950 items-center lg:px-32'>
              <h1>Recommended</h1>
              <p className='w-20 h-1 bg-green-700'></p>
            </div>
            <Products product={recommended} />
          </div>
        }
        {
          <div className='mt-28'>
            <div className='flex gap-3 px-5 mb-5 text-3xl font-bold text-sky-950 items-center lg:px-32'>
              <h1>Fruits and vegetables</h1>
              <p className='w-20 h-1 bg-green-700'></p>
            </div>
            <Products product={vegetableData} />
          </div>
        }
        {
          <div className='mt-28'>
            <div className='flex gap-3 px-5 mb-5 text-3xl font-bold text-sky-950 items-center lg:px-32'>
              <h1>Packaged products</h1>
              <p className='w-20 h-1 bg-green-700'></p>
            </div>
            <Products product={PackagedProductsData} />
          </div>
        }
        {
          <div className='mt-28'>
            <div className='flex gap-3 px-5 mb-5 text-3xl font-bold text-sky-950 items-center lg:px-32'>
              <h1>Hygiene and personal care</h1>
              <p className='w-20 h-1 bg-green-700'></p>
            </div>
            <Products product={higieneCareData} />
          </div>
        }
        {
          <div className='mt-28'>
            <div className='flex gap-3 px-5 mb-5 text-3xl font-bold text-sky-950 items-center lg:px-32'>
              <h1>Drunks</h1>
              <p className='w-20 h-1 bg-green-700'></p>
            </div>
            <Products product={drunkData} />
          </div>
        }
      </main>
    </>
  )
}
